name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  camera:
    # When depending on this package from a real application you should use:
    #   camera: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  camera_android_camerax:
    path: '../../camera_android_camerax/'
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  video_player: ^2.7.0
  image_picker: ^1.0.2
  path: ^1.8.2
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_face_mesh_detection: ^0.2.0
  google_mlkit_pose_detection: ^0.12.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
